version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_user_password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sample_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis:
    image: redis
    command: redis-server --requirepass YOUR_ROOT_PWD
    ports:
      - '6380:6380'
    volumes:
      - ./redis_data:/data

      
  web:
    image: joehwang/rails6:ruby3
    build: .
    entrypoint: rails server
    command: -p 3000 -b 0.0.0.0 --pid ./tmp/pids/serv.pid -e development
    environment:
      EDITOR: "vim"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./rails_app:/sample_app
    ports:
      - "33033:3000"
    depends_on:
      - db
    tty: true